# src/patterns/Api_Endpoint_Patterns.py
# Centralized and expanded API endpoint path patterns for WebScann3r

api_endpoint_patterns = [
    '/api/',
    '/service/',
    '/services/',
    '/v1/',
    '/v2/',
    '/v3/',
    '/graphql',
    '/rest/',
    '.json',
    '.xml',
    '/rpc',
    '/ws',
    '/websocket',
    '/endpoint',
    '/data/',
    '/feed/',
    '/openapi',
    '/swagger',
    '/soap',
    '/odata',
    '/actuator',
    '/admin/api/',
    '/internal/api/',
    '/external/api/',
    '/public/api/',
    '/private/api/',
    '/api-docs',
    '/restapi',
    '/restful',
    '/jsonrpc',
    '/xmlrpc',
    '/apiv2/',
    '/apiv3/',
    '/v4/',
    '/v5/',
    '/mobileapi/',
    '/api/v1/',
    '/api/v2/',
    '/api/v3/',
    '/api/v4/',
    '/api/v5/',
]
