# All patterns for CSRF Vulnerabilities
csrf_vulnerabilities_patterns = [
    r'(?i)csrf_token\s*=\s*[\'"]\s*[\'"]\s*',
    r'(?i)anticsrf\s*=\s*[\'"]\s*[\'"]\s*',
    r'(?i)_csrf\s*=\s*[\'"]\s*[\'"]\s*',
    r'(?i)<form[^>]*method=[\'"]post[\'"][^>]*>(?:(?!csrf).)*<\/form>',
    r'(?i)\.setRequestHeader\([\'"]X-CSRF-Token[\'"]\s*,\s*[\'"][\'"]\)',
    r'(?i)\.setRequestHeader\([\'"]X-CSRF-Token[\'"]\s*,\s*null\)',
    # Expanded patterns
    r'(?i)csrfmiddlewaretoken\s*=\s*[\'"]?\s*[\'"]?',  # Django
    r'(?i)xsrf_token\s*=\s*[\'"]?\s*[\'"]?',  # Angular/Google
    r'(?i)csrf\s*:\s*null',
    r'(?i)csrf\s*=\s*None',
    r'(?i)csrf_protect\s*=\s*False',
    r'(?i)@csrf_exempt',
    r'(?i)@csrf_protect\s*#?\s*off',
    r'(?i)csrfProtection\s*:\s*false',
    r'(?i)csrf_protection\s*=\s*false',
    r'(?i)csrf_enabled\s*=\s*false',
    r'(?i)csrf_disable\s*=\s*true',
    r'(?i)csrf_disabled\s*=\s*true',
    r'(?i)csrf_token\s*:\s*null',
    r'(?i)csrf_token\s*:\s*None',
    r'(?i)csrf_token\s*:\s*""',
    r'(?i)csrf_token\s*:\s*\'\'',
    r'(?i)csrf_token\s*=\s*""',
    r'(?i)csrf_token\s*=\s*\'\'',
    r'(?i)csrf_token\s*=\s*None',
    r'(?i)csrf_token\s*=\s*null',
    r'(?i)csrf_token\s*=\s*False',
    r'(?i)csrf_token\s*=\s*0',
    r'(?i)csrf_token\s*=\s*undefined',
    r'(?i)csrf_token\s*=\s*NaN',
    r'(?i)csrf_token\s*=\s*empty',
    r'(?i)csrf_token\s*=\s*void',
    r'(?i)csrf_token\s*=\s*nil',
    r'(?i)csrf_token\s*=\s*no',
    r'(?i)csrf_token\s*=\s*off',
    r'(?i)csrf_token\s*=\s*disable',
    r'(?i)csrf_token\s*=\s*disabled',
    r'(?i)csrf_token\s*=\s*notset',
    r'(?i)csrf_token\s*=\s*unset',
    r'(?i)csrf_token\s*=\s*empty',
    r'(?i)csrf_token\s*=\s*blank',
]