# Path Traversal patterns (expanded and commented)
path_traversal_patterns = [
    # Basic ../ and ..\\ patterns
    r'\.\./',
    r'\.\.\\',
    r'\.\./\.\./',
    r'\.\.\\.\.\\',
    # URL encoded traversal
    r'%2e%2e%2f',
    r'%2e%2e/',
    r'%2e%2e%5c',
    r'%252e%252e%255c',
    r'%c0%ae%c0%ae%c0%af',
    r'%c1%1c%c1%1c',
    r'%252e%252e%252f',
    r'%252e%252e%255c',
    r'%255c%255c',
    # Null byte injection
    r'\.\./\x00',
    r'\.\.\\\x00',
    r'%00',
    # Directory traversal with file
    r'\.\./etc/passwd',
    r'\.\./etc/shadow',
    r'\.\./boot.ini',
    r'\.\./windows/win.ini',
    r'\.\./winnt/win.ini',
    r'\.\./windows/system32/drivers/etc/hosts',
    r'\.\./proc/self/environ',
    r'\.\./.htpasswd',
    r'\.\./.git/config',
    r'\.\./.ssh/id_rsa',
    r'\.\./.bash_history',
    r'\.\./.aws/credentials',
    r'\.\./.docker/config.json',
    r'\.\./.npmrc',
    r'\.\./.env',
    r'\.\./.config',
    r'\.\./.svn/entries',
    r'\.\./.hg/hgrc',
    r'\.\./.bzr/branch/branch.conf',
    # Traversal with appended extensions
    r'\.\./etc/passwd%00',
    r'\.\./etc/shadow%00',
    r'\.\./boot.ini%00',
    r'\.\./windows/win.ini%00',
    r'\.\./winnt/win.ini%00',
    r'\.\./windows/system32/drivers/etc/hosts%00',
    r'\.\./proc/self/environ%00',
    r'\.\./.htpasswd%00',
    r'\.\./.git/config%00',
    r'\.\./.ssh/id_rsa%00',
    r'\.\./.bash_history%00',
    r'\.\./.aws/credentials%00',
    r'\.\./.docker/config.json%00',
    r'\.\./.npmrc%00',
    r'\.\./.env%00',
    r'\.\./.config%00',
    r'\.\./.svn/entries%00',
    r'\.\./.hg/hgrc%00',
    r'\.\./.bzr/branch/branch.conf%00',
    # Traversal with traversal bypass tricks
    r'\.\./;/etc/passwd',
    r'\.\./;/etc/shadow',
    r'\.\./;/boot.ini',
    r'\.\./;/windows/win.ini',
    r'\.\./;/winnt/win.ini',
    r'\.\./;/windows/system32/drivers/etc/hosts',
    r'\.\./;/proc/self/environ',
    r'\.\./;/.htpasswd',
    r'\.\./;/.git/config',
    r'\.\./;/.ssh/id_rsa',
    r'\.\./;/.bash_history',
    r'\.\./;/.aws/credentials',
    r'\.\./;/.docker/config.json',
    r'\.\./;/.npmrc',
    r'\.\./;/.env',
    r'\.\./;/.config',
    r'\.\./;/.svn/entries',
    r'\.\./;/.hg/hgrc',
    r'\.\./;/.bzr/branch/branch.conf',
    # Traversal with unicode
    r'\.\./\u2215etc\u2215passwd',
    r'\.\./\u2215etc\u2215shadow',
    r'\.\./\u2215boot.ini',
    r'\.\./\u2215windows\u2215win.ini',
    r'\.\./\u2215winnt\u2215win.ini',
    r'\.\./\u2215windows\u2215system32\u2215drivers\u2215etc\u2215hosts',
    r'\.\./\u2215proc\u2215self\u2215environ',
    r'\.\./\u2215.htpasswd',
    r'\.\./\u2215.git\u2215config',
    r'\.\./\u2215.ssh\u2215id_rsa',
    r'\.\./\u2215.bash_history',
    r'\.\./\u2215.aws\u2215credentials',
    r'\.\./\u2215.docker\u2215config.json',
    r'\.\./\u2215.npmrc',
    r'\.\./\u2215.env',
    r'\.\./\u2215.config',
    r'\.\./\u2215.svn\u2215entries',
    r'\.\./\u2215.hg\u2215hgrc',
    r'\.\./\u2215.bzr\u2215branch\u2215branch.conf',
    # Additional bypass tricks and encodings
    r'\.\./\.\./',  # Double traversal
    r'\.\./\.\./\.\./',  # Triple traversal
    r'\.\./\.\./\.\./\.\./',  # Quad traversal
    r'\.\./\.\./\.\./\.\./\.\./',  # Five-level traversal
    r'\.\./\.\./\\.\\.\\',  # Mixed slashes
    r'\.\./\\.\\.\\',  # Mixed slashes
    r'\.\./%2e%2e/',  # Mixed encoding
    r'\.\./%252e%252e/',  # Double encoding
    r'\.\./%c0%ae%c0%ae/',  # Unicode encoding
    r'\.\./%c1%1c%c1%1c/',  # Unicode encoding
    # Path traversal in function arguments (generic)
    r'open\s*\(\s*["\']?\.\./',
    r'fopen\s*\(\s*["\']?\.\./',
    r'File\s*\(\s*["\']?\.\./',
    r'fs\.readFile\s*\(\s*["\']?\.\./',
    r'fs\.createReadStream\s*\(\s*["\']?\.\./',
    r'fs\.writeFile\s*\(\s*["\']?\.\./',
    r'fs\.appendFile\s*\(\s*["\']?\.\./',
    r'fs\.open\s*\(\s*["\']?\.\./',
    r'os\.open\s*\(\s*["\']?\.\./',
    r'os\.read\s*\(\s*["\']?\.\./',
    r'os\.write\s*\(\s*["\']?\.\./',
    r'os\.remove\s*\(\s*["\']?\.\./',
    r'os\.unlink\s*\(\s*["\']?\.\./',
    r'os\.rmdir\s*\(\s*["\']?\.\./',
    r'os\.rename\s*\(\s*["\']?\.\./',
]
