# Patterns for Prototype Pollution (expanded and well-commented)
prototype_pollution_patterns = [
    # Direct property names (classic)
    r'(?i)["\']__proto__["\']',
    r'(?i)["\']constructor["\']',
    r'(?i)["\']prototype["\']',
    r'(?i)["\']prototype_chain["\']',
    r'(?i)["\']__defineGetter__["\']',
    r'(?i)["\']__defineSetter__["\']',
    r'(?i)["\']__lookupGetter__["\']',
    r'(?i)["\']__lookupSetter__["\']',
    r'(?i)["\']__noSuchMethod__["\']',
    r'(?i)["\']__parent__["\']',
    r'(?i)["\']__proto__',
    r'(?i)\b__proto__\b',
    r'(?i)\bconstructor\b',
    r'(?i)\bprototype\b',
    r'(?i)\bprototype_chain\b',
    r'(?i)\b__defineGetter__\b',
    r'(?i)\b__defineSetter__\b',
    r'(?i)\b__lookupGetter__\b',
    r'(?i)\b__lookupSetter__\b',
    r'(?i)\b__noSuchMethod__\b',
    r'(?i)\b__parent__\b',
    # Encoded property names
    r'(?i)%5f%5fproto%5f%5f',
    r'(?i)%5f%5fproto%5f%5f',
    r'(?i)%5f%5fdefineGetter%5f%5f',
    r'(?i)%5f%5fdefineSetter%5f%5f',
    r'(?i)%5f%5flookupGetter%5f%5f',
    r'(?i)%5f%5flookupSetter%5f%5f',
    r'(?i)%5f%5fnoSuchMethod%5f%5f',
    r'(?i)%5f%5fparent%5f%5f',
    r'(?i)%255f%255fproto%255f%255f',
    r'(?i)%255f%255fdefineGetter%255f%255f',
    r'(?i)%255f%255fdefineSetter%255f%255f',
    r'(?i)%255f%255flookupGetter%255f%255f',
    r'(?i)%255f%255flookupSetter%255f%255f',
    r'(?i)%255f%255fnoSuchMethod%255f%255f',
    r'(?i)%255f%255fparent%255f%255f',
    # Unicode/hex encoded
    r'(?i)\\u005f\\u005fproto\\u005f\\u005f',
    r'(?i)\\x5f\\x5fproto\\x5f\\x5f',
    r'(?i)\\u005f\\u005fdefineGetter\\u005f\\u005f',
    r'(?i)\\u005f\\u005fdefineSetter\\u005f\\u005f',
    r'(?i)\\u005f\\u005flookupGetter\\u005f\\u005f',
    r'(?i)\\u005f\\u005flookupSetter\\u005f\\u005f',
    # Dot/bracket notation
    r'(?i)\.(?:__proto__|constructor|prototype|prototype_chain|__defineGetter__|__defineSetter__|__lookupGetter__|__lookupSetter__|__noSuchMethod__|__parent__)',
    r'(?i)\[(?:"|\')?(?:__proto__|constructor|prototype|prototype_chain|__defineGetter__|__defineSetter__|__lookupGetter__|__lookupSetter__|__noSuchMethod__|__parent__)(?:"|\')?\]',
    # Nested property assignment
    r'(?i)\bset\s*\(\s*["\']?(?:__proto__|constructor|prototype|prototype_chain)["\']?',
    r'(?i)\bassign\s*\(\s*["\']?(?:__proto__|constructor|prototype|prototype_chain)["\']?',
    # Common JS/TS/Node methods
    r'(?i)Object\.defineProperty\(',
    r'(?i)Object\.setPrototypeOf\(',
    r'(?i)Object\.assign\(',
    r'(?i)Object\.create\(',
    r'(?i)Object\.defineProperties\(',
    r'(?i)Reflect\.setPrototypeOf\(',
    r'(?i)Reflect\.defineProperty\(',
    r'(?i)Reflect\.defineProperties\(',
    r'(?i)Reflect\.construct\(',
    # Popular libraries
    r'(?i)\bdeepmerge\(',
    r'(?i)\bmerge\(',
    # r'(?i)\bextend\(', # Commented: too broad, causes false positives on common JS usage like jQuery.extend()
    # r'(?i)\bjQuery.extend\(', # Commented: too broad, causes false positives on common JS usage
    # r'(?i)\$\.extend\(', # Commented: too broad, causes false positives on common JS usage
    r'(?i)\bdefaults\(',
    r'(?i)\bassignIn\(',
    r'(?i)\bmergeWith\(',
    r'(?i)\bdefaultsDeep\(',
    r'(?i)\b_.merge\(',
    r'(?i)\b_.extend\(',
    r'(?i)\b_.defaults\(',
    r'(?i)\b_.assign\(',
    r'(?i)\b$.extend\(',
    r'(?i)\b$.merge\(',
    r'(?i)\b$.fn.extend\(',
    r'(?i)\b$.fn.merge\(',
    r'(?i)\bjQuery.extend\(',
    r'(?i)\bjQuery.merge\(',
    # Query string/JSON/HTTP param patterns
    r'(?i)[?&](?:__proto__|constructor|prototype|prototype_chain|__defineGetter__|__defineSetter__|__lookupGetter__|__lookupSetter__|__noSuchMethod__|__parent__)=',
    r'(?i)\{\s*["\']?(?:__proto__|constructor|prototype|prototype_chain|__defineGetter__|__defineSetter__|__lookupGetter__|__lookupSetter__|__noSuchMethod__|__parent__)["\']?\s*:',
    r'(?i)\bbody\s*\.\s*(?:__proto__|constructor|prototype|prototype_chain)\b',
    r'(?i)\bparams\s*\.\s*(?:__proto__|constructor|prototype|prototype_chain)\b',
    r'(?i)\bquery\s*\.\s*(?:__proto__|constructor|prototype|prototype_chain)\b',
    r'(?i)\bdata\s*\.\s*(?:__proto__|constructor|prototype|prototype_chain)\b',
    # REST/GraphQL
    r'(?i)mutation\s*\{[^}]*?(?:__proto__|constructor|prototype|prototype_chain)[^}]*?\}',
    r'(?i)query\s*\{[^}]*?(?:__proto__|constructor|prototype|prototype_chain)[^}]*?\}',
    # Bypass tricks (spaces, tabs, newlines, dots, etc.)
    r'(?i)["\']?\s*__proto__\s*["\']?',
    r'(?i)["\']?\s*constructor\s*["\']?',
    r'(?i)["\']?\s*prototype\s*["\']?',
    r'(?i)["\']?\s*prototype_chain\s*["\']?',
    r'(?i)["\']?\s*__defineGetter__\s*["\']?',
    r'(?i)["\']?\s*__defineSetter__\s*["\']?',
    r'(?i)["\']?\s*__lookupGetter__\s*["\']?',
    r'(?i)["\']?\s*__lookupSetter__\s*["\']?',
    r'(?i)["\']?\s*__noSuchMethod__\s*["\']?',
    r'(?i)["\']?\s*__parent__\s*["\']?',
    # Double property assignment
    r'(?i)\bset\s*\(.*(?:__proto__|constructor|prototype|prototype_chain).*,.*(?:__proto__|constructor|prototype|prototype_chain).*\)',
    # Array/object merge with dangerous keys
    r'(?i)\bmerge\s*\(.*(?:__proto__|constructor|prototype|prototype_chain).*\)',
    r'(?i)\bdeepmerge\s*\(.*(?:__proto__|constructor|prototype|prototype_chain).*\)',
    r'(?i)\bextend\s*\(.*(?:__proto__|constructor|prototype|prototype_chain).*\)',
    # JSON with dangerous keys
    r'(?i)\{\s*["\']?__proto__["\']?\s*:',
    r'(?i)\{\s*["\']?constructor["\']?\s*:',
    r'(?i)\{\s*["\']?prototype["\']?\s*:',
    r'(?i)\{\s*["\']?prototype_chain["\']?\s*:',
    # HTTP form fields
    r'(?i)name=["\']?__proto__["\']?',
    r'(?i)name=["\']?constructor["\']?',
    r'(?i)name=["\']?prototype["\']?',
    r'(?i)name=["\']?prototype_chain["\']?',
    # Miscellaneous
    r'(?i)\bsetPrototypeOf\b',
    r'(?i)\bdefineProperty\b',
    r'(?i)\bdefineProperties\b',
    r'(?i)\bassign\b',
    r'(?i)\bmerge\b',
    r'(?i)\bdeepmerge\b',
    #r'(?i)\bextend\b',
    r'(?i)\bdefaults\b',
    r'(?i)\bassignIn\b',
    r'(?i)\bmergeWith\b',
    r'(?i)\bdefaultsDeep\b',
    r'(?i)\bObject\.prototype\b',
    r'(?i)\bFunction\.prototype\b',
    r'(?i)\bArray\.prototype\b',
    r'(?i)\bString\.prototype\b',
    r'(?i)\bNumber\.prototype\b',
    r'(?i)\bBoolean\.prototype\b',
    r'(?i)\bRegExp\.prototype\b',
    r'(?i)\bDate\.prototype\b',
    r'(?i)\bError\.prototype\b',
    r'(?i)\bMap\.prototype\b',
    r'(?i)\bSet\.prototype\b',
    r'(?i)\bWeakMap\.prototype\b',
    r'(?i)\bWeakSet\.prototype\b',
    r'(?i)\bSymbol\.prototype\b',
    r'(?i)\bBigInt\.prototype\b',
    r'(?i)\bReflect\.prototype\b',
    r'(?i)\bProxy\.prototype\b',
    r'(?i)\bIntl\.prototype\b',
    r'(?i)\bJSON\.prototype\b',
    r'(?i)\bMath\.prototype\b',
    r'(?i)\bPromise\.prototype\b',
    r'(?i)\bGenerator\.prototype\b',
    r'(?i)\bAsyncFunction\.prototype\b',
    r'(?i)\bGeneratorFunction\.prototype\b',
    r'(?i)\bAsyncGeneratorFunction\.prototype\b',
    r'(?i)\bAsyncGenerator\.prototype\b',
    r'(?i)\bReflect\b',
    r'(?i)\bProxy\b',
    r'(?i)\bIntl\b',
    r'(?i)\bJSON\b',
    r'(?i)\bMath\b',
    r'(?i)\bPromise\b',
    r'(?i)\bGenerator\b',
    r'(?i)\bAsyncFunction\b',
    r'(?i)\bGeneratorFunction\b',
    r'(?i)\bAsyncGeneratorFunction\b',
    r'(?i)\bAsyncGenerator\b',
]
