# src/patterns/Server_Patterns.py
# Centralized and expanded server version regex patterns for WebScann3r

server_patterns = [
    r'apache[\/\s-](\d+\.\d+\.\d+)',
    r'nginx[\/\s-](\d+\.\d+\.\d+)',
    r'microsoft-iis[\/\s-](\d+\.\d+)',
    r'lighttpd[\/\s-](\d+\.\d+\.\d+)',
    r'caddy[\/\s-](\d+\.\d+\.\d+)',
    r'gunicorn[\/\s-](\d+\.\d+\.\d+)',
    r'cherokee[\/\s-](\d+\.\d+\.\d+)',
    r'openresty[\/\s-](\d+\.\d+\.\d+)',
    r'jetty[\/\s-](\d+\.\d+\.\d+)',
    r'tomcat[\/\s-](\d+\.\d+\.\d+)',
    r'glassfish[\/\s-](\d+\.\d+\.\d+)',
    r'wsgiserver[\/\s-](\d+\.\d+\.\d+)',
    r'webrick[\/\s-](\d+\.\d+\.\d+)',
    r'grizzly[\/\s-](\d+\.\d+\.\d+)',
    r'httpd[\/\s-](\d+\.\d+\.\d+)',
    r'ibm-http-server[\/\s-](\d+\.\d+\.\d+)',
    r'oracle-http-server[\/\s-](\d+\.\d+\.\d+)',
    r'zeus[\/\s-](\d+\.\d+\.\d+)',
    r'litespeed[\/\s-](\d+\.\d+\.\d+)',
    r'lotus-domino[\/\s-](\d+\.\d+\.\d+)',
    r'boa[\/\s-](\d+\.\d+\.\d+)',
    r'roadrunner[\/\s-](\d+\.\d+\.\d+)',
    r'python[\/\s-](\d+\.\d+\.\d+)',
    r'perl[\/\s-](\d+\.\d+\.\d+)',
    r'ruby[\/\s-](\d+\.\d+\.\d+)',
    r'php[\/\s-](\d+\.\d+\.\d+)',
    r'go[\/\s-](\d+\.\d+\.\d+)',
    r'node\.js[\/\s-](\d+\.\d+\.\d+)',
    r'express[\/\s-](\d+\.\d+\.\d+)',
    r'koa[\/\s-](\d+\.\d+\.\d+)',
    r'hapi[\/\s-](\d+\.\d+\.\d+)',
    r'fastify[\/\s-](\d+\.\d+\.\d+)',
    r'swoole[\/\s-](\d+\.\d+\.\d+)',
    r'tornado[\/\s-](\d+\.\d+\.\d+)',
    r'uwsgi[\/\s-](\d+\.\d+\.\d+)',
    r'apache-coyote[\/\s-](\d+\.\d+\.\d+)',
    r'jboss[\/\s-](\d+\.\d+\.\d+)',
    r'wildfly[\/\s-](\d+\.\d+\.\d+)',
    r'websphere[\/\s-](\d+\.\d+\.\d+)',
    r'weblogic[\/\s-](\d+\.\d+\.\d+)',
]
