# src/patterns/XPowered_Patterns.py
# Centralized and expanded X-Powered-By technology/version regex patterns for WebScann3r

xpowered_patterns = [
    r'php[\/\s-](\d+\.\d+\.\d+)',
    r'php[\/\s-](\d+\.\d+)',
    r'asp\.net',
    r'express[\/\s-]?(\d+\.\d+\.\d+)?',
    r'rails[\/\s-](\d+\.\d+\.\d+)',
    r'laravel[\/\s-](\d+\.\d+\.\d+)',
    r'symfony[\/\s-](\d+\.\d+\.\d+)',
    r'django[\/\s-](\d+\.\d+\.\d+)',
    r'flask[\/\s-](\d+\.\d+\.\d+)',
    r'node\.js[\/\s-](\d+\.\d+\.\d+)',
    r'koa[\/\s-](\d+\.\d+\.\d+)',
    r'hapi[\/\s-](\d+\.\d+\.\d+)',
    r'fastify[\/\s-](\d+\.\d+\.\d+)',
    r'go[\/\s-](\d+\.\d+\.\d+)',
    r'java[\/\s-](\d+\.\d+\.\d+)',
    r'python[\/\s-](\d+\.\d+\.\d+)',
    r'ruby[\/\s-](\d+\.\d+\.\d+)',
    r'perl[\/\s-](\d+\.\d+\.\d+)',
    r'wordpress[\/\s-](\d+\.\d+\.\d+)',
    r'joomla[\/\s-](\d+\.\d+\.\d+)',
    r'drupal[\/\s-](\d+\.\d+\.\d+)',
    r'angular[\/\s-](\d+\.\d+\.\d+)',
    r'react[\/\s-](\d+\.\d+\.\d+)',
    r'veu[\/\s-](\d+\.\d+\.\d+)',
    r'next[\/\s-](\d+\.\d+\.\d+)',
    r'nuxt[\/\s-](\d+\.\d+\.\d+)',
    r'ember[\/\s-](\d+\.\d+\.\d+)',
    r'backbone[\/\s-](\d+\.\d+\.\d+)',
    r'jquery[\/\s-](\d+\.\d+\.\d+)',
    r'bootstrap[\/\s-](\d+\.\d+\.\d+)',
    r'vue[\/\s-](\d+\.\d+\.\d+)',
    r'cakephp[\/\s-](\d+\.\d+\.\d+)',
    r'codeigniter[\/\s-](\d+\.\d+\.\d+)',
    r'zend[\/\s-](\d+\.\d+\.\d+)',
    r'yii[\/\s-](\d+\.\d+\.\d+)',
    r'slim[\/\s-](\d+\.\d+\.\d+)',
    r'fuelphp[\/\s-](\d+\.\d+\.\d+)',
    r'phalcon[\/\s-](\d+\.\d+\.\d+)',
    r'silex[\/\s-](\d+\.\d+\.\d+)',
    r'cake[\/\s-](\d+\.\d+\.\d+)',
]
